/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHECryptoSeerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMyPrediction"
      | "getUserPrediction"
      | "hasPredicted"
      | "predict"
      | "protocolId"
      | "updatePrediction"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMyPrediction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPrediction",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPredicted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predict",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrediction",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMyPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPredicted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "predict", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePrediction",
    data: BytesLike
  ): Result;
}

export interface FHECryptoSeer extends BaseContract {
  connect(runner?: ContractRunner | null): FHECryptoSeer;
  waitForDeployment(): Promise<this>;

  interface: FHECryptoSeerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMyPrediction: TypedContractMethod<[], [string], "view">;

  getUserPrediction: TypedContractMethod<[user: AddressLike], [string], "view">;

  hasPredicted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  predict: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  updatePrediction: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMyPrediction"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUserPrediction"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasPredicted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "predict"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePrediction"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
